spring.application.name=idvalidation
server.port=9095
spring.datasource.url=jdbc:postgresql://10.217.190.10:5432/True-Value-CRM
spring.datasource.username=application_user
spring.datasource.password=z$K8R2lk4L.(EIgMM|I)z~p>??BX

